export const ADD_EQUATION = 'ADD_EQUATION';
export const FETCH_EQUATION = 'FETCH_EQUATION';
export const FETCH_ALL_EQUATIONS = 'FETCH_ALL_EQUATIONS';
export const FETCH_EQUATIONS = 'FETCH_EQUATIONS';
export const UPDATE_EQUATION = 'UPDATE_EQUATION';
export const DELETE_EQUATION = 'DELETE_EQUATION';

export const ADD_EQUATION_ERROR = 'ADD_EQUATION_ERROR';
export const ADD_EQUATION_SUCCESS = 'ADD_EQUATION_SUCCESS';
