export const ADD_EQUATION = 'ADD_EQUATION';
export const ADD_EQUATION_ERROR = 'ADD_EQUATION_ERROR';
export const ADD_EQUATION_SUCCESS = 'ADD_EQUATION_SUCCESS';

export const FETCH_EQUATION = 'FETCH_EQUATION';
export const FETCH_EQUATION_SUCCESS = 'FETCH_EQUATION_SUCCESS';
export const FETCH_EQUATION_ERROR = 'FETCH_EQUATION_ERROR';

export const FETCH_ALL_EQUATIONS = 'FETCH_ALL_EQUATIONS';
export const FETCH_ALL_EQUATIONS_SUCCESS = 'FETCH_ALL_EQUATIONS_SUCCESS';
export const FETCH_ALL_EQUATIONS_ERROR = 'FETCH_ALL_EQUATIONS_ERROR';

export const UPDATE_EQUATION = 'UPDATE_EQUATION';
export const UPDATE_EQUATION_SUCCESS = 'UPDATE_EQUATION_SUCCESS';
export const UPDATE_EQUATION_ERROR = 'UPDATE_EQUATION_ERROR';
