export const FETCH_ALL_SUBJECTS = 'FETCH_ALL_SUBJECTS';
export const FETCH_ALL_SUBJECTS_ERROR = 'FETCH_ALL_SUBJECTS_ERROR';
export const FETCH_ALL_SUBJECTS_SUCCESS = 'FETCH_ALL_SUBJECTS_SUCCESS';

export const ADD_SUBJECT = 'ADD_SUBJECT';
export const ADD_SUBJECT_SUCCESS = 'ADD_SUBJECT_SUCCESS';
export const ADD_SUBJECT_ERROR = 'ADD_SUBJECT_ERROR';

export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS';
export const UPDATE_SUBJECT_ERROR = 'UPDATE_SUBJECT_ERROR';
