export const FETCH_ALL_TOPICS = 'FETCH_ALL_TOPICS';
export const FETCH_ALL_TOPICS_ERROR = 'FETCH_ALL_TOPICS_ERROR';
export const FETCH_ALL_TOPICS_SUCCESS = 'FETCH_ALL_TOPICS_SUCCESS';
export const FETCH_ALL_TOPICS_DONE = 'FETCH_ALL_TOPICS_DONE';

export const ADD_TOPIC = 'ADD_TOPIC';
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
export const ADD_TOPIC_ERROR = 'ADD_TOPIC_ERROR';

export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';
export const FETCH_TOPICS_DONE = 'FETCH_TOPICS_DONE';

export const UPDATE_TOPIC = 'UPDATE_TOPIC';
export const UPDATE_TOPIC_SUCCESS = 'UPDATE_TOPIC_SUCCESS';
export const UPDATE_TOPIC_ERROR = 'UPDATE_TOPIC_ERROR';

export const DELETE_TOPIC = 'DELETE_TOPIC';
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_ERROR = 'DELETE_TOPIC_ERROR';
