export const FETCH_ALL_TOPICS = 'FETCH_ALL_TOPICS';
export const FETCH_ALL_TOPICS_ERROR = 'FETCH_ALL_TOPICS_ERROR';
export const FETCH_ALL_TOPICS_SUCCESS = 'FETCH_ALL_TOPICS_SUCCESS';

export const ADD_TOPIC = 'ADD_TOPIC';
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
export const ADD_TOPIC_ERROR = 'ADD_TOPIC_ERROR';

export const FETCH_TOPICS = 'FETCH_TOPICS';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_ERROR = 'FETCH_TOPICS_ERROR';
